### ISSUE TITLE
Invalid response status: 404

### ISSUE THREAD

**Issue by riderx** [TestArmada/magellan-saucelabs-executor#16]
since today when i run magellan with sauce-lab i get error when downloading sauce-connect, i was working before and i change nothing in my conf :/
i have 
export SAUCE_CONNECT_VERSION="4.4.7"
i have try without i get the same problem ...
```
[INFO] [Saucelabs Executor] Sauce configuration OK
Missing Sauce Connect local proxy, downloading dependency
This will only happen once.
Invalid response status: 404
[ERROR] [Saucelabs Executor] Failed to download sauce connect binary:
[ERROR] [Saucelabs Executor] Error: Download failed with status code: 404
[ERROR] [Saucelabs Executor] sauce-connect-launcher will attempt to re-download next time it is run.
[ERROR] [Magellan] Error initializing Magellan
[ERROR] [Magellan] Error description:
[ERROR] [Magellan] Error: Download failed with status code: 404
[ERROR] [Magellan] Error stack trace:
[ERROR] [Magellan] Error: Download failed with status code: 404
    at ClientRequest.<anonymous> (/Users/martindonadieu/Project/toucantoco/Lark/node_modules/sauce-connect-launcher/lib/sauce-connect-launcher.js:219:23)
    at emitOne (events.js:120:20)
    at ClientRequest.emit (events.js:210:7)
    at HTTPParser.parserOnIncomingClient (_http_client.js:564:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
    at TLSSocket.socketOnData (_http_client.js:453:20)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
error Command failed with exit code 1.
```

**Comment by riderx** [comment]
i forget to put --sauce_tunnel_config tunnel.json sorry
